const db = require('../config/db');
const { generateReceiptPDF } = require('../utils/pdfGenerator');

const createPayment = async (req, res) => {
    const { member_id, period_month, period_year, amount, method, proof_url } = req.body;
    const userId = req.user.id;

    try {
        // 1. Validate Member
        const memberRes = await db.query('SELECT * FROM members WHERE id = $1', [member_id]);
        if (memberRes.rows.length === 0) return res.status(404).json({ message: 'Member not found' });
        if (memberRes.rows[0].status !== 'active') return res.status(400).json({ message: 'Member is inactive' });

        // 2. Check for duplicate
        const dupRes = await db.query(
            'SELECT id FROM payments WHERE member_id = $1 AND period_month = $2 AND period_year = $3',
            [member_id, period_month, period_year]
        );
        if (dupRes.rows.length > 0) return res.status(400).json({ message: 'Payment for this period already exists' });

        // 3. Insert Payment (invoice_number generated by DB trigger)
        const payRes = await db.query(
            'INSERT INTO payments (member_id, period_month, period_year, amount, method, proof_url) VALUES ($1, $2, $3, $4, $5, $6) RETURNING *',
            [member_id, period_month, period_year, amount, method, proof_url]
        );

        const payment = payRes.rows[0];

        // 4. Get User Details for PDF
        const userRes = await db.query('SELECT full_name FROM users WHERE id = (SELECT user_id FROM members WHERE id = $1)', [member_id]);
        const fullName = userRes.rows[0].full_name;

        // 5. Generate PDF (In a real app, you'd upload this to cloud storage)
        // For this demonstration, we return the base64 or a success message
        const pdfBytes = await generateReceiptPDF({
            invoice_number: payment.invoice_number,
            full_name: fullName,
            period: `${period_month}/${period_year}`,
            payment_date: payment.payment_date.toISOString().split('T')[0],
            method: payment.method,
            amount: payment.amount
        });

        // 6. Update receipt_pdf_url (Optional: logic to upload to S3/Cloudinary would go here)
        // For now, we simulate a URL
        const simulatedUrl = `https://storage.lightweb.app/receipts/receipt-${payment.invoice_number}.pdf`;
        await db.query('UPDATE payments SET receipt_pdf_url = $1 WHERE id = $2', [simulatedUrl, payment.id]);

        res.status(201).json({
            message: 'Payment recorded successfully',
            payment: { ...payment, receipt_pdf_url: simulatedUrl }
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

const getMyPayments = async (req, res) => {
    try {
        const result = await db.query(
            'SELECT p.* FROM payments p JOIN members m ON p.member_id = m.id WHERE m.user_id = $1 ORDER BY p.payment_date DESC',
            [req.user.id]
        );
        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

const getAllPayments = async (req, res) => {
    try {
        const result = await db.query(
            'SELECT p.*, u.full_name FROM payments p JOIN members m ON p.member_id = m.id JOIN users u ON m.user_id = u.id ORDER BY p.payment_date DESC'
        );
        res.json(result.rows);
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

module.exports = { createPayment, getMyPayments, getAllPayments };
